package com.itworks.snamp.adapters.rest;

import com.itworks.snamp.Consumer;
import com.itworks.snamp.ExceptionPlaceholder;
import com.itworks.snamp.ExceptionalCallable;
import com.itworks.snamp.SafeConsumer;
import com.itworks.snamp.adapters.AbstractResourceAdapter;
import com.itworks.snamp.core.OsgiLoggingContext;
import com.itworks.snamp.internal.Utils;
import org.eclipse.jetty.jaas.JAASLoginService;
import org.eclipse.jetty.jaas.spi.LdapLoginModule;
import org.eclipse.jetty.server.UserIdentity;
import org.eclipse.jetty.websocket.server.WebSocketServerFactory;

import javax.ws.rs.WebApplicationException;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.SecurityContext;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author Roman Sakno
 * @version 1.0
 * @since 1.0
 */
final class RestAdapterHelpers {
    static final String ADAPTER_NAME = "REST";
    private static final String LOGGER_NAME = AbstractResourceAdapter.getLoggerName(ADAPTER_NAME);

    private RestAdapterHelpers(){

    }

    /**
     * Represents monitor role that can receive notifications and read attributes.
     */
    static final String MONITOR_ROLE = "monitor";

    /**
     * Represents maintainer role that can overwrite attributes.
     */
    static final String MAINTAINER_ROLE = "maintainer";

    private static final class OsgiCompliantJaasLoginService extends JAASLoginService{
        private final ClassLoader osgiClassLoader;

        private OsgiCompliantJaasLoginService(final ClassLoader osgiClassLoader){
            this.osgiClassLoader = osgiClassLoader;
        }

        @Override
        public UserIdentity login(final String username, final Object credentials) {
            return Utils.withContextClassLoader(osgiClassLoader, new ExceptionalCallable<UserIdentity, ExceptionPlaceholder>() {
                @Override
                public UserIdentity call() {
                    return OsgiCompliantJaasLoginService.super.login(username, credentials);
                }
            });
        }
    }

    static JAASLoginService createJaasLoginServiceForOsgi(final ClassLoader osgiClassLoader) {
        return new OsgiCompliantJaasLoginService(osgiClassLoader);
    }

    //this method is not used by this bundle but required for correct Import-Package
    //header generated by maven-bundle-plugin. This plugin adds org.eclipse.jetty.jaas.spi.*
    //package that is required by LoginContext factory.
    @SuppressWarnings("UnusedDeclaration")
    static String convertCredentialJettyToLdap(final String encryptedPassword){
        return LdapLoginModule.convertCredentialLdapToJetty(encryptedPassword);
    }

    static void checkRoles(final SecurityContext context, final String... roles) throws WebApplicationException {
        if(context == null) return;
        for(final String r: roles)
            if(context.isUserInRole(r)) return;
        throw new WebApplicationException(new SecurityException(String.format("User %s is not in %s roles", context.getUserPrincipal().getName(), Arrays.toString(roles))), Response.Status.FORBIDDEN);
    }

    static void maintainerRequired(final SecurityContext context){
        checkRoles(context, MAINTAINER_ROLE);
    }

    static void wellKnownRoleRequired(final SecurityContext context){
        checkRoles(context, MAINTAINER_ROLE, MONITOR_ROLE);
    }

    //org.eclipse.jetty.websocket.server package should be imported explicitly, therefore
    //this stub method required for maven-bundle-plugin
    @SuppressWarnings("UnusedDeclaration")
    static Object getActiveUpgradeContext(){
        return WebSocketServerFactory.getActiveUpgradeContext();
    }

    static <E extends Exception> void withLogger(final Consumer<Logger, E> contextBody) throws E {
        OsgiLoggingContext.within(LOGGER_NAME, contextBody);
    }

    private static void log(final Level lvl, final String message, final Object[] args, final Throwable e){
        withLogger(new SafeConsumer<Logger>() {
            @Override
            public void accept(final Logger logger) {
                logger.log(lvl, String.format(message, args), e);
            }
        });
    }

    static void log(final Level lvl, final String message, final Throwable e){
        log(lvl, message, new Object[0], e);
    }

    static void log(final Level lvl, final String message, final Object arg0, final Throwable e){
        log(lvl, message, new Object[]{arg0}, e);
    }

}
